---
- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - ufw
    - fail2ban

- name: Start and enable UFW
  ufw:
    state: enabled

- name: Establish default incoming firewall rule
  ufw:
    policy: deny
    direction: incoming

- name: Establish default outgoing firewall rule
  ufw:
    policy: allow
    direction: outgoing

- name: Allow ports in firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ports_allow }}"

- name: Enable rate limiting
  ufw:
    rule: limit
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ports_allow }}"

- name: Configure fail2ban
  copy:
    src: jail.local
    dest: "/etc/fail2ban/"
    owner: root
    group: root
    mode: 0644
