---
- name: Ensure apt cache is up to date.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Checking if base_path exists
  stat:
    path: "{{ base_path }}/"
  register: base_path

- name: Create base_path directory
  become: true
  become_user: "{{ ansible_user }}"
  file:
    path: "{{ base_path }}"
    state: directory
  when: base_path.stat.exists == False
